chore: [#57093] Fix `mirrors-mypy` rev in `.pre-commit-config.yaml`
Previously, I encountered:

```
mrw@mrwvm:~/src/os2mo-data-import-and-export/integrations/SD_Lon$ poetry
run pre-commit run
[INFO] Initializing environment for
https://github.com/pre-commit/mirrors-mypy.
An unexpected error has occurred: CalledProcessError: command:
('/usr/bin/git', 'checkout', 'v1.00')
return code: 1
stdout: (none)
stderr:
    error: pathspec 'v1.00' did not match any file(s) known to git
Check the log at /home/mrw/.cache/pre-commit/pre-commit.log
```

After fixing the rev, I also encountered:
```
mrw@mrwvm:~/src/os2mo-data-import-and-export/integrations/SD_Lon$ poetry
run pre-commit run
[INFO] Initializing environment for
https://github.com/pre-commit/mirrors-mypy.
[ERROR] The hook `mypy` specifies `additional_dependencies` but is using
language `system` which does not install an environment.  Perhaps you
meant to use a specific language?
```

I removed the lines:
```
additional_dependencies:
  - pydantic
```
which seems to fix this.