fix: [#57423] Use `ancestors_validity` instead of `ancestors`
This should hopefully work around this issue:
```
gql.transport.exceptions.TransportQueryError: Expected exactly one item
in iterable, but got OrganisationUnitRead(...), and perhaps more.

GraphQL request:10:9
 9 |         name
10 |         ancestors {
   |         ^
11 |           name
```
i.e. receiving more than one org unit for each element in `ancestors`,
due to having more than one version of the same org unit.